/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRedemptionGateway__factory } from './IRedemptionGateway__factory.js';
export { IReserveRegistry__factory } from './IReserveRegistry__factory.js';