/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IReserveRegistry, IReserveRegistryInterface } from "../../interfaces/IReserveRegistry.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "allowed",
        "type": "bool"
      }
    ],
    "name": "AllowedSignerUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "reportId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint64",
        "name": "asOfTimestamp",
        "type": "uint64"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "attestedFineGoldGrams",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "merkleRoot",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "barListHash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "signer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint64",
        "name": "publishedAt",
        "type": "uint64"
      }
    ],
    "name": "AttestationPublished",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "reportId",
        "type": "bytes32"
      }
    ],
    "name": "exists",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "reportId",
        "type": "bytes32"
      }
    ],
    "name": "getAttestation",
    "outputs": [
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "asOfTimestamp",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "publishedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "attestedFineGoldGrams",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "merkleRoot",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "barListHash",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "signer",
            "type": "address"
          }
        ],
        "internalType": "struct IReserveRegistry.AttestationRecord",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "start",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "count",
        "type": "uint256"
      }
    ],
    "name": "getReportIds",
    "outputs": [
      {
        "internalType": "bytes32[]",
        "name": "out",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "signer",
        "type": "address"
      }
    ],
    "name": "isAllowedSigner",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestAsOfTimestamp",
    "outputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestAttestation",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "reportId",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "asOfTimestamp",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "publishedAt",
            "type": "uint64"
          },
          {
            "internalType": "uint256",
            "name": "attestedFineGoldGrams",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "merkleRoot",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "barListHash",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "signer",
            "type": "address"
          }
        ],
        "internalType": "struct IReserveRegistry.AttestationRecord",
        "name": "rec",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestReportId",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "reportId",
        "type": "bytes32"
      },
      {
        "internalType": "uint64",
        "name": "asOfTimestamp",
        "type": "uint64"
      },
      {
        "internalType": "uint256",
        "name": "attestedFineGoldGrams",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "merkleRoot",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "barListHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "signature",
        "type": "bytes"
      }
    ],
    "name": "publishAttestation",
    "outputs": [
      {
        "internalType": "address",
        "name": "recoveredSigner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "reportIdsCount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IReserveRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IReserveRegistryInterface {
      return new Interface(_abi) as IReserveRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IReserveRegistry {
      return new Contract(address, _abi, runner) as unknown as IReserveRegistry;
    }
  }
  