/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'GRUSHToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GRUSHToken__factory>
getContractFactory(name: 'IRedemptionGateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRedemptionGateway__factory>
getContractFactory(name: 'IReserveRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReserveRegistry__factory>
getContractFactory(name: 'RedemptionGateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.RedemptionGateway__factory>
getContractFactory(name: 'ReserveRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReserveRegistry__factory>

  getContractAt(name: 'GRUSHToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GRUSHToken>
getContractAt(name: 'IRedemptionGateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRedemptionGateway>
getContractAt(name: 'IReserveRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReserveRegistry>
getContractAt(name: 'RedemptionGateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.RedemptionGateway>
getContractAt(name: 'ReserveRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReserveRegistry>

  deployContract(name: 'GRUSHToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GRUSHToken>
deployContract(name: 'IRedemptionGateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRedemptionGateway>
deployContract(name: 'IReserveRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReserveRegistry>
deployContract(name: 'RedemptionGateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RedemptionGateway>
deployContract(name: 'ReserveRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReserveRegistry>

  deployContract(name: 'GRUSHToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GRUSHToken>
deployContract(name: 'IRedemptionGateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRedemptionGateway>
deployContract(name: 'IReserveRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReserveRegistry>
deployContract(name: 'RedemptionGateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.RedemptionGateway>
deployContract(name: 'ReserveRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReserveRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  