/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace RedemptionGateway {
      
    export type RedemptionRequestStruct = {requester: AddressLike, amount: BigNumberish, createdAt: BigNumberish, status: BigNumberish, destinationHash: BytesLike, decisionRef: BytesLike, decidedAt: BigNumberish, decidedBy: AddressLike}

    export type RedemptionRequestStructOutput = [requester: string, amount: bigint, createdAt: bigint, status: bigint, destinationHash: string, decisionRef: string, decidedAt: bigint, decidedBy: string] & {requester: string, amount: bigint, createdAt: bigint, status: bigint, destinationHash: string, decisionRef: string, decidedAt: bigint, decidedBy: string }
  
    }

  export interface RedemptionGatewayInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "OPERATOR_ROLE" | "PAUSER_ROLE" | "cancelRedemption" | "escrowBalance" | "fulfillRedemption" | "getRequest" | "getRoleAdmin" | "grantRole" | "grush" | "grushPermit" | "hasRole" | "pause" | "paused" | "rejectRedemption" | "renounceRole" | "requestRedemption" | "requestRedemptionWithPermit" | "revokeRole" | "statusOf" | "supportsInterface" | "totalEscrowed" | "unpause" | "userNonce"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Paused" | "RedemptionCancelled" | "RedemptionFulfilled" | "RedemptionRejected" | "RedemptionRequested" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelRedemption', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'escrowBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'fulfillRedemption', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRequest', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'grush', values?: undefined): string;
encodeFunctionData(functionFragment: 'grushPermit', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectRedemption', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestRedemption', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'requestRedemptionWithPermit', values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'statusOf', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'totalEscrowed', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'userNonce', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fulfillRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grush', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grushPermit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRedemptionWithPermit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'statusOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEscrowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userNonce', data: BytesLike): Result;
  }

  
    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionCancelledEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, cancelledAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, cancelledAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, cancelledAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionFulfilledEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, fulfillmentRef: BytesLike, decidedBy: AddressLike, decidedAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, fulfillmentRef: string, decidedBy: string, decidedAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, fulfillmentRef: string, decidedBy: string, decidedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionRejectedEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, reasonHash: BytesLike, decidedBy: AddressLike, decidedAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, reasonHash: string, decidedBy: string, decidedAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, reasonHash: string, decidedBy: string, decidedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionRequestedEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, destinationHash: BytesLike, createdAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, destinationHash: string, createdAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, destinationHash: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RedemptionGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): RedemptionGateway;
    waitForDeployment(): Promise<this>;

    interface: RedemptionGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancelRedemption: TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    escrowBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fulfillRedemption: TypedContractMethod<
      [requestId: BytesLike, fulfillmentRef: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRequest: TypedContractMethod<
      [requestId: BytesLike, ],
      [RedemptionGateway.RedemptionRequestStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grush: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    grushPermit: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    rejectRedemption: TypedContractMethod<
      [requestId: BytesLike, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestRedemption: TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    requestRedemptionWithPermit: TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    statusOf: TypedContractMethod<
      [requestId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    totalEscrowed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    userNonce: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancelRedemption'): TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fulfillRedemption'): TypedContractMethod<
      [requestId: BytesLike, fulfillmentRef: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [requestId: BytesLike, ],
      [RedemptionGateway.RedemptionRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grush'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grushPermit'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rejectRedemption'): TypedContractMethod<
      [requestId: BytesLike, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRedemption'): TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRedemptionWithPermit'): TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'statusOf'): TypedContractMethod<
      [requestId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'totalEscrowed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userNonce'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RedemptionCancelled'): TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
getEvent(key: 'RedemptionFulfilled'): TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
getEvent(key: 'RedemptionRejected'): TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
getEvent(key: 'RedemptionRequested'): TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RedemptionCancelled(bytes32,address,uint256,uint64)': TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
      RedemptionCancelled: TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
    

      'RedemptionFulfilled(bytes32,address,uint256,bytes32,address,uint64)': TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
      RedemptionFulfilled: TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
    

      'RedemptionRejected(bytes32,address,uint256,bytes32,address,uint64)': TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
      RedemptionRejected: TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
    

      'RedemptionRequested(bytes32,address,uint256,bytes32,uint64)': TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;
      RedemptionRequested: TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }