/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ReserveRegistry {
      
    export type AttestationRecordStruct = {asOfTimestamp: BigNumberish, publishedAt: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signer: AddressLike}

    export type AttestationRecordStructOutput = [asOfTimestamp: bigint, publishedAt: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string] & {asOfTimestamp: bigint, publishedAt: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string }
  
    }

  export interface ReserveRegistryInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "PAUSER_ROLE" | "PUBLISHER_ROLE" | "RESERVE_ATTESTATION_TYPEHASH" | "SIGNER_ADMIN_ROLE" | "eip712Domain" | "exists" | "getAttestation" | "getReportIds" | "getRoleAdmin" | "grantRole" | "hasRole" | "isAllowedSigner" | "latestAsOfTimestamp" | "latestAttestation" | "latestReportId" | "pause" | "paused" | "publishAttestation" | "renounceRole" | "reportIdsCount" | "revokeRole" | "setAllowedSigner" | "setAllowedSigners" | "supportsInterface" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowedSignerUpdated" | "AttestationPublished" | "EIP712DomainChanged" | "Paused" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PUBLISHER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'RESERVE_ATTESTATION_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'SIGNER_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'exists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAttestation', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getReportIds', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isAllowedSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestAsOfTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestAttestation', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestReportId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishAttestation', values: [BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'reportIdsCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setAllowedSigner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setAllowedSigners', values: [AddressLike[], boolean[]]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PUBLISHER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RESERVE_ATTESTATION_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SIGNER_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReportIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllowedSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAsOfTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestReportId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportIdsCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowedSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAllowedSigners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace AllowedSignerUpdatedEvent {
      export type InputTuple = [signer: AddressLike, allowed: boolean];
      export type OutputTuple = [signer: string, allowed: boolean];
      export interface OutputObject {signer: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AttestationPublishedEvent {
      export type InputTuple = [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signer: AddressLike, publishedAt: BigNumberish];
      export type OutputTuple = [reportId: string, asOfTimestamp: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string, publishedAt: bigint];
      export interface OutputObject {reportId: string, asOfTimestamp: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string, publishedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ReserveRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ReserveRegistry;
    waitForDeployment(): Promise<this>;

    interface: ReserveRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PUBLISHER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    RESERVE_ATTESTATION_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SIGNER_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    exists: TypedContractMethod<
      [reportId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getAttestation: TypedContractMethod<
      [reportId: BytesLike, ],
      [ReserveRegistry.AttestationRecordStructOutput],
      'view'
    >
    

    
    getReportIds: TypedContractMethod<
      [start: BigNumberish, count: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isAllowedSigner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    latestAsOfTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latestAttestation: TypedContractMethod<
      [],
      [[string, ReserveRegistry.AttestationRecordStructOutput] & {reportId: string, rec: ReserveRegistry.AttestationRecordStructOutput }],
      'view'
    >
    

    
    latestReportId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    publishAttestation: TypedContractMethod<
      [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signature: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    reportIdsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setAllowedSigner: TypedContractMethod<
      [signer: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setAllowedSigners: TypedContractMethod<
      [signers: AddressLike[], allowed: boolean[], ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PUBLISHER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'RESERVE_ATTESTATION_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SIGNER_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [reportId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAttestation'): TypedContractMethod<
      [reportId: BytesLike, ],
      [ReserveRegistry.AttestationRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getReportIds'): TypedContractMethod<
      [start: BigNumberish, count: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isAllowedSigner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'latestAsOfTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latestAttestation'): TypedContractMethod<
      [],
      [[string, ReserveRegistry.AttestationRecordStructOutput] & {reportId: string, rec: ReserveRegistry.AttestationRecordStructOutput }],
      'view'
    >;
getFunction(nameOrSignature: 'latestReportId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'publishAttestation'): TypedContractMethod<
      [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signature: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportIdsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAllowedSigner'): TypedContractMethod<
      [signer: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAllowedSigners'): TypedContractMethod<
      [signers: AddressLike[], allowed: boolean[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllowedSignerUpdated'): TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
getEvent(key: 'AttestationPublished'): TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'AllowedSignerUpdated(address,bool)': TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
      AllowedSignerUpdated: TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
    

      'AttestationPublished(bytes32,uint64,uint256,bytes32,bytes32,address,uint64)': TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;
      AttestationPublished: TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }