apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-deployment
  template:
    metadata:
      labels:
        app: worker-deployment
    spec:
      containers:
        - name: worker-deployment
          image: REPLACE_ME
          ports:
            - containerPort: 3000
