/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRedemptionGateway } from './IRedemptionGateway.js';
export type { IReserveRegistry } from './IReserveRegistry.js';