/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IRedemptionGateway {
      
    export type RedemptionRequestStruct = {requester: AddressLike, amount: BigNumberish, createdAt: BigNumberish, status: BigNumberish, destinationHash: BytesLike, decisionRef: BytesLike, decidedAt: BigNumberish, decidedBy: AddressLike}

    export type RedemptionRequestStructOutput = [requester: string, amount: bigint, createdAt: bigint, status: bigint, destinationHash: string, decisionRef: string, decidedAt: bigint, decidedBy: string] & {requester: string, amount: bigint, createdAt: bigint, status: bigint, destinationHash: string, decisionRef: string, decidedAt: bigint, decidedBy: string }
  
    }

  export interface IRedemptionGatewayInterface extends Interface {
    getFunction(nameOrSignature: "cancelRedemption" | "escrowBalance" | "fulfillRedemption" | "getRequest" | "rejectRedemption" | "requestRedemption" | "requestRedemptionWithPermit" | "statusOf"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RedemptionCancelled" | "RedemptionFulfilled" | "RedemptionRejected" | "RedemptionRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelRedemption', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'escrowBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'fulfillRedemption', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getRequest', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'rejectRedemption', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'requestRedemption', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'requestRedemptionWithPermit', values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'statusOf', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'cancelRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fulfillRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRedemptionWithPermit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'statusOf', data: BytesLike): Result;
  }

  
    export namespace RedemptionCancelledEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, cancelledAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, cancelledAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, cancelledAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionFulfilledEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, fulfillmentRef: BytesLike, decidedBy: AddressLike, decidedAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, fulfillmentRef: string, decidedBy: string, decidedAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, fulfillmentRef: string, decidedBy: string, decidedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionRejectedEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, reasonHash: BytesLike, decidedBy: AddressLike, decidedAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, reasonHash: string, decidedBy: string, decidedAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, reasonHash: string, decidedBy: string, decidedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionRequestedEvent {
      export type InputTuple = [requestId: BytesLike, requester: AddressLike, amount: BigNumberish, destinationHash: BytesLike, createdAt: BigNumberish];
      export type OutputTuple = [requestId: string, requester: string, amount: bigint, destinationHash: string, createdAt: bigint];
      export interface OutputObject {requestId: string, requester: string, amount: bigint, destinationHash: string, createdAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IRedemptionGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRedemptionGateway;
    waitForDeployment(): Promise<this>;

    interface: IRedemptionGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelRedemption: TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    escrowBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    fulfillRedemption: TypedContractMethod<
      [requestId: BytesLike, fulfillmentRef: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getRequest: TypedContractMethod<
      [requestId: BytesLike, ],
      [IRedemptionGateway.RedemptionRequestStructOutput],
      'view'
    >
    

    
    rejectRedemption: TypedContractMethod<
      [requestId: BytesLike, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestRedemption: TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    requestRedemptionWithPermit: TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    statusOf: TypedContractMethod<
      [requestId: BytesLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelRedemption'): TypedContractMethod<
      [requestId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrowBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fulfillRedemption'): TypedContractMethod<
      [requestId: BytesLike, fulfillmentRef: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [requestId: BytesLike, ],
      [IRedemptionGateway.RedemptionRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'rejectRedemption'): TypedContractMethod<
      [requestId: BytesLike, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRedemption'): TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRedemptionWithPermit'): TypedContractMethod<
      [amount: BigNumberish, destinationHash: BytesLike, deadline: BigNumberish, v: BigNumberish, r: BytesLike, s: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'statusOf'): TypedContractMethod<
      [requestId: BytesLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'RedemptionCancelled'): TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
getEvent(key: 'RedemptionFulfilled'): TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
getEvent(key: 'RedemptionRejected'): TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
getEvent(key: 'RedemptionRequested'): TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;

    filters: {
      
      'RedemptionCancelled(bytes32,address,uint256,uint64)': TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
      RedemptionCancelled: TypedContractEvent<RedemptionCancelledEvent.InputTuple, RedemptionCancelledEvent.OutputTuple, RedemptionCancelledEvent.OutputObject>;
    

      'RedemptionFulfilled(bytes32,address,uint256,bytes32,address,uint64)': TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
      RedemptionFulfilled: TypedContractEvent<RedemptionFulfilledEvent.InputTuple, RedemptionFulfilledEvent.OutputTuple, RedemptionFulfilledEvent.OutputObject>;
    

      'RedemptionRejected(bytes32,address,uint256,bytes32,address,uint64)': TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
      RedemptionRejected: TypedContractEvent<RedemptionRejectedEvent.InputTuple, RedemptionRejectedEvent.OutputTuple, RedemptionRejectedEvent.OutputObject>;
    

      'RedemptionRequested(bytes32,address,uint256,bytes32,uint64)': TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;
      RedemptionRequested: TypedContractEvent<RedemptionRequestedEvent.InputTuple, RedemptionRequestedEvent.OutputTuple, RedemptionRequestedEvent.OutputObject>;
    
    };
  }