/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IReserveRegistry {
      
    export type AttestationRecordStruct = {asOfTimestamp: BigNumberish, publishedAt: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signer: AddressLike}

    export type AttestationRecordStructOutput = [asOfTimestamp: bigint, publishedAt: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string] & {asOfTimestamp: bigint, publishedAt: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string }
  
    }

  export interface IReserveRegistryInterface extends Interface {
    getFunction(nameOrSignature: "exists" | "getAttestation" | "getReportIds" | "isAllowedSigner" | "latestAsOfTimestamp" | "latestAttestation" | "latestReportId" | "publishAttestation" | "reportIdsCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowedSignerUpdated" | "AttestationPublished"): EventFragment;

    encodeFunctionData(functionFragment: 'exists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getAttestation', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getReportIds', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isAllowedSigner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestAsOfTimestamp', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestAttestation', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestReportId', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishAttestation', values: [BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'reportIdsCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'exists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getReportIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllowedSigner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAsOfTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestReportId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishAttestation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reportIdsCount', data: BytesLike): Result;
  }

  
    export namespace AllowedSignerUpdatedEvent {
      export type InputTuple = [signer: AddressLike, allowed: boolean];
      export type OutputTuple = [signer: string, allowed: boolean];
      export interface OutputObject {signer: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AttestationPublishedEvent {
      export type InputTuple = [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signer: AddressLike, publishedAt: BigNumberish];
      export type OutputTuple = [reportId: string, asOfTimestamp: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string, publishedAt: bigint];
      export interface OutputObject {reportId: string, asOfTimestamp: bigint, attestedFineGoldGrams: bigint, merkleRoot: string, barListHash: string, signer: string, publishedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IReserveRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IReserveRegistry;
    waitForDeployment(): Promise<this>;

    interface: IReserveRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    exists: TypedContractMethod<
      [reportId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getAttestation: TypedContractMethod<
      [reportId: BytesLike, ],
      [IReserveRegistry.AttestationRecordStructOutput],
      'view'
    >
    

    
    getReportIds: TypedContractMethod<
      [start: BigNumberish, count: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    isAllowedSigner: TypedContractMethod<
      [signer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    latestAsOfTimestamp: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latestAttestation: TypedContractMethod<
      [],
      [[string, IReserveRegistry.AttestationRecordStructOutput] & {reportId: string, rec: IReserveRegistry.AttestationRecordStructOutput }],
      'view'
    >
    

    
    latestReportId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publishAttestation: TypedContractMethod<
      [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signature: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    reportIdsCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'exists'): TypedContractMethod<
      [reportId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getAttestation'): TypedContractMethod<
      [reportId: BytesLike, ],
      [IReserveRegistry.AttestationRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getReportIds'): TypedContractMethod<
      [start: BigNumberish, count: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'isAllowedSigner'): TypedContractMethod<
      [signer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'latestAsOfTimestamp'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latestAttestation'): TypedContractMethod<
      [],
      [[string, IReserveRegistry.AttestationRecordStructOutput] & {reportId: string, rec: IReserveRegistry.AttestationRecordStructOutput }],
      'view'
    >;
getFunction(nameOrSignature: 'latestReportId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishAttestation'): TypedContractMethod<
      [reportId: BytesLike, asOfTimestamp: BigNumberish, attestedFineGoldGrams: BigNumberish, merkleRoot: BytesLike, barListHash: BytesLike, signature: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reportIdsCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AllowedSignerUpdated'): TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
getEvent(key: 'AttestationPublished'): TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;

    filters: {
      
      'AllowedSignerUpdated(address,bool)': TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
      AllowedSignerUpdated: TypedContractEvent<AllowedSignerUpdatedEvent.InputTuple, AllowedSignerUpdatedEvent.OutputTuple, AllowedSignerUpdatedEvent.OutputObject>;
    

      'AttestationPublished(bytes32,uint64,uint256,bytes32,bytes32,address,uint64)': TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;
      AttestationPublished: TypedContractEvent<AttestationPublishedEvent.InputTuple, AttestationPublishedEvent.OutputTuple, AttestationPublishedEvent.OutputObject>;
    
    };
  }